#!/bin/sh
code --install-extension adambaldwin.vscode-nsp
code --install-extension aeschli.vscode-css-formatter
code --install-extension akmittal.hugofy
code --install-extension be5invis.toml
code --install-extension carolynvs.dep
code --install-extension chenxsan.vscode-standardjs
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension felipe.nasc-touchbar
code --install-extension humao.rest-client
code --install-extension jock.svg
code --install-extension kamikillerto.vscode-colorize
code --install-extension maty.vscode-mocha-sidebar
code --install-extension mauve.terraform
code --install-extension michelemelluso.code-beautifier
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension robertohuertasm.vscode-icons
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension slevesque.vscode-hexdump
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension wholroyd.HCL
code --install-extension zhuangtongfa.Material-theme
code --install-extension zxh404.vscode-proto3
