#!/bin/sh
code --install-extension adambaldwin.vscode-nsp
code --install-extension aeschli.vscode-css-formatter
code --install-extension akmittal.hugofy
code --install-extension Antyos.openscad
code --install-extension bbenoist.Nix
code --install-extension be5invis.toml
code --install-extension bierner.markdown-mermaid
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension carolynvs.dep
code --install-extension casualjim.gotemplate
code --install-extension chenxsan.vscode-standardjs
code --install-extension dbaeumer.vscode-eslint
code --install-extension dongfg.vscode-beancount-formatter
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension felipe.nasc-touchbar
code --install-extension formulahendry.github-actions
code --install-extension GitHub.codespaces
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-labs
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension Grafana.vscode-jsonnet
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension James-Yu.latex-workshop
code --install-extension jock.svg
code --install-extension kamikillerto.vscode-colorize
code --install-extension Leathong.openscad-language-support
code --install-extension Lencerf.beancount
code --install-extension michelemelluso.code-beautifier
code --install-extension mindaro-dev.file-downloader
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-serial-monitor
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryu1kn.edit-with-shell
code --install-extension ryu1kn.partial-diff
code --install-extension slevesque.vscode-hexdump
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension vscode-icons-team.vscode-icons
code --install-extension zhuangtongfa.material-theme
code --install-extension zxh404.vscode-proto3
